PLATFORM=linux
ARCH=x64
HAVE_ALSA=1

CC=gcc
LD=gcc
CFLAGS=-DPLATFORM_LINUX -DARCH_X64 -DHAVE_ALSA -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE
LDFLAGS=

OPTIMIZEFLAGS=-O2 -fomit-frame-pointer -ffast-math 
DEBUGFLAGS=-ggdb3 
